DATASET:
    NAME: "stanford2d3d_pan"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    WORKERS: 0
TRAIN:
    EPOCHS: 40
    BATCH_SIZE: 1
    CROP_SIZE: (1080,1080)
    BASE_SIZE: 1080
    BACKBONE_PRETRAINED_PATH: "pretrained/mit_b2.pth"
    MODEL_SAVE_DIR: 'workdirs/stanford2d3d_pan/trans4pass_small_1080x1080/'
    APEX: False
TEST:
    BATCH_SIZE: 1
    TEST_MODEL_PATH: "workdirs/stanford2d3d_pan/trans4pass_small_1080x1080/trans4pass_small_pan_F1.pth"
    CROP_SIZE: (1080,1080)

SOLVER:
    OPTIMIZER: "adamw"
    LR: 0.00025

MODEL:
    MODEL_NAME: "Trans4PASS"
    BACKBONE: "trans4pass_v2"
    EMB_CHANNELS: 128
    USE_DCN: [True, False, False, False]
    USE_DEDE: [True, True, True, True]

AUG:
    CROP: True